version: '3'

services:

  api:
    container_name: api
    restart: always
    image: api
    build: ./src/Web
    environment:
      - ECHO_PORT=5002
      - ECHO_HOST=echo
      - API_EXTERNAL_HOST=api
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    depends_on:
      - echo
    ports:
      - "5000:5000"
      - "5001:5001"

  echo:
    container_name: echo
    build: ./src/EchoConsoleApp
    restart: always
    environment:
      - ECHO_EXTERNAL_HOST=echo
    ports:
      - "5002:5002"

